version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_USER: "notes"
      POSTGRES_PASSWORD: "Amir2003"
    volumes:
      - "db:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  db:
  redis: