# Generated by Django 4.1.1 on 2022-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_note_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='alert_send_at',
            field=models.DateTimeField(null=True),
        ),
    ]
