# Generated by Django 4.1.1 on 2022-11-13 08:15

from django.utils.datetime_safe import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_note_alert_send_at_alter_note_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('created_at',), 'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('alert_send_at__gte', datetime(2022, 1, 1, 0, 0)), ('alert_send_at__isnull', False)), ('alert_send_at__isnull', True), _connector='OR'), name='alert_send_at_after'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('title', 'text'), name='unique_content'),
        ),
    ]
