# Generated by Django 4.1.1 on 2022-11-29 09:39

from django.db import migrations
import stdimage.models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_note_image_alter_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=web.models.get_note_image_path, variations={'thumbnail': {'height': 400, 'width': 400}}, verbose_name='Картинка'),
        ),
    ]
