version: '3'

services:
  app:
    image: django2k:latest
    build:
      dockerfile: deploy/Dockerfile
      context: ..
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
        DB_HOST: "db"
        DB_PORT: "5432"
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_USER: "notes"
      POSTGRES_PASSWORD: "Amir2003"
    volumes:
      - "db:/var/lib/postgresql/data"


volumes:
  db:

