version: '3'

services:
  nginx:
    image: django2k-nginx:latest
    build:
      context: ..
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static:/app/static

  app:
    image: django2k:latest
    build:
      dockerfile: deploy/app/Dockerfile
      context: ..
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
    restart: always
    volumes:
      - static:/app/static

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_USER: "notes"
      POSTGRES_PASSWORD: "Amir2003"
    volumes:
      - "db:/var/lib/postgresql/data"


volumes:
  db:
  static:

