# Generated by Django 4.1.4 on 2022-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_note_is_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(help_text="Название заметки", max_length=500, verbose_name="Название"),
        ),
    ]
