# Generated by Django 4.1.4 on 2022-12-23 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_alter_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notecomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
        ),
    ]
